baseURL = "https://nickmcccleery.github.io"
languageCode = "en-gb"
title = "Nick McCleery"
theme = 'archie'
pygmentsstyle = "paraiso-dark"
pygmentscodefences = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[params]
mode = "toggle"
useCDN = false
subtitle = "Aut inveniam viam aut faciam"
mathjax = true
katex = true
favicon = "https://img.icons8.com/ios-filled/500w/gears.png"
customcss = ["css/overrides.css"]

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/nick-mccleery/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nick_mccleery"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nickmccleery"

[[params.social]]
name = "CV"
icon = "file-text"
url = "/cv"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
