baseURL = "https://nickmcccleery.github.io"
languageCode = "en-gb"
title = "Nick McCleery"
theme = 'archie'
pygmentsstyle = "paraiso-dark"
pygmentscodefences = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
mode = "toggle"
useCDN = false
subtitle = "This website is an irregularly updated collection of things I've written. Most of these articles are related to engineering, software, or startups. <br/><br/> _Aut inveniam viam aut faciam._"
mathjax = true
katex = true
favicon = "https://img.icons8.com/ios-filled/500w/gears.png"
customcss = ["css/overrides.css"]

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:contact@nickmccleery.com"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/nick-mccleery/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nick_mccleery"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nickmccleery"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tools"
url = "/tools"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
